title: GISKES
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.125
  brandStrength: 0.0625
  rhythmicContrast: 0.5
  brandColors:
    - '#393226'
    - '#050404'
    - '#915C4B'
    - '#FBB49A'
    - '#FFF2D0'
  lightness: 0.3125
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Giskes
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1039427
layout_spectrum: 1
