title: null
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.9301075
  lightness: 0.9982079
  brandColors:
    - '#FFFFFF'
    - '#0A0D12'
    - '#A6A6A6'
    - '#7E7E7E'
    - '#2D2838'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Giskes
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.61238
layout_spectrum: 0.3136201
