name: Giskes
favicon: null
layout_spectrum: 0.4910394
typography_spectrum: 0.46152
title: GISKES
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f1e'
    - '#fcfcfc'
    - '#565553'
    - '#201c1b'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.3781362
  rhythmicContrast: 1
purpose: []
