layout_spectrum: 1
color:
  saturation: 1
  brandStrength: 0.9211469
  lightness: 0.374552
  rhythmicContrast: 1
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.6021506
name: Giskes
