name: Giskes
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6021506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aa9faf'
    - '#e0c5cc'
    - '#746b6e'
    - '#2e292d'
    - '#fefeff'
  brandStrength: 0.9211469
  lightness: 0.374552
  saturation: 1
  rhythmicContrast: 1
purpose: []
