name: Giskes
favicon: null
layout_spectrum: 0.49351
typography_spectrum: 0.1039427
title: GISKES
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000912'
    - '#f1ffff'
    - '#847150'
    - '#2fa199'
    - '#740000'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
