typography_spectrum: 0.46152
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 1
title: GISKES
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.3781362
  brandStrength: 0.1875
  rhythmicContrast: 1
  brandColors:
    - '#ffffff'
    - '#231f1e'
    - '#fcfcfc'
    - '#565553'
    - '#201c1b'
  lightness: 0.6875
purpose: []
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Giskes
